---
title: ""
pagetitle: Karissa Whiting
---

```{r results = "asis", echo = FALSE, message=FALSE, warning= FALSE, fig.height=5, fig.width=4, out.width= "40%", out.height= "80%", out.extra='style="float:left; padding:15px"'}

require(raster)
require(ggplot2)

pulsar = function(n){
  x = seq(0,100, length=n)
  norms = dnorm(x, mean=40, sd=6)*100 + dnorm(x, mean=60, sd=6)*50
  noise1 = approx(sample(c(rep(0:8,2),18:19)), n = n, y=NULL)$y
  noise2 = approx(sample(0:50), n = n, y=NULL)$y
  noise3 = rnorm(n)
  abs(norms + norms * noise1 + norms * noise2 * .1 + noise3)
}

d = apply(sapply(rep(100,50), pulsar), 1, rev)
d = data.frame(rasterToPoints(raster(d)))
d$elev = d$layer + d$y * 1200

p = ggplot() + 
#  labs(x = 'UNKNOWN PLEASURES', y = NULL, title = 'JOY DIVISION') + 
  theme_minimal() +
  theme(axis.ticks = element_blank(),
      panel.grid = element_blank(),
      axis.text = element_blank(),
  
    plot.background = element_rect(fill = "white"), 
    axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(), 
    axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()
    #  plot.title = element_text(colour = 'white', size = 76, hjust = .5),
    #  axis.title.x = element_text(colour = 'white', size = 43)
    )

for(g in unique(d$y)){
  dat = subset(d, y == g)
  p = p + geom_polygon(data=dat, aes(x, elev), fill='#114b5f',
                       alpha = .7) + 
    geom_line(data=dat, aes(x, elev), col='#114b5f', alpha=.5) + 
    xlim(c(.1, .85))
}

p + xlab("") + ylab("")

```

I am a Research Biostatistician at [Memorial Sloan Kettering Cancer Center](https://www.mskcc.org/) in New York City where my research focuses on leveraging multi-modal genomic, radiology and pathology data to characterize cancer risk and predict clinical outcomes. 

I have experience in design, implementation and analysis of clinical trials, as well as retrospective and prospective observational studies. Additionally, I have previous experience in design, development, and validation of digital surveillance tools for assessing emerging infectious disease threats, and currently work with MSK's hospital infectious disease team to monitor and assess the ongoing COVID-19 pandemic.


I earned my M.S. in Biostatistics at Columbia University’s Mailman School of Public Health. 

I am an R enthusiast with an interest in creating software tools to help researchers build reproducible analysis pipelines. 


<br>

### Contact Information

Email: [karissa.whiting@gmail.com](mailto:karissa.whiting@gmail.com)
Phone: seven one six eight six eight four two seven seven


